CS3250-IllegalSkillsException/myDatabase

Database.java, Main.java
Co-authored-by: Samuel Vang <smvang7@gmail.com>
Closes #21 
I needed to make a few changes to the table. All incoming orders are given an id to avoid duplicate entry errors. 
The ids are assigned to the orders sequentially. The first ID is 1. The next ID is 2, and so on.
This is the setup for the table now, please ensure you replicate it when testing.
Keep in mind that because of the way MySQL sorts databases, you will see something like this when you view it:
This does not mean that orders were skipped over. It is sorting the data alphanumerically, so you can still find 2 if you scroll down a lot. See here:
=> Method to simulate incoming customer order data in the database.

Database.java, Inventory.java, Main.java
A lot of these changes seem to just be from formatting. Primary change is the addition of the Search function, which splits into 2 sub-menus: 1 for inventory table and 1 for orders table. Each menu takes 1 filter and displays table results that match the filter. Currently only allows a single filter. Would like to expand that to multiple simultaneous filters in the future.
=> Added new search function with compatibility for both db tables

DiscordBot.java
This is the very basics of a discord chat bot. Richard and I will work off of this as we do our user story. The process of setting this up is a little complicated. You will need to import a library and create an artifact. I will allow you to use my bot token for testing TEMPORARILY.
=> Discord chat bot basics.

DiscordBot.java, OnlineUser.java
DISCORD BOT COMMANDS:
!login (email) (password)
Logs into the discord bot as the user. Some users do not have passwords and a warning is given when such a login occurs.
!logout
Logs out of the discord bot if you are logged in.
!orders
If you are logged in, shows your orders in the database.
=> Discord bot: login, logout, and view of past orders.

.gitignore, .vscode/settings.json, DiscordBot.java, OnlineUser.java
added getRecommend and getUnder20 functions to the discord bot. getRecommend will recommend a random product depending on the user's location. getUnder20 will show a list of product under 20 that can be paged by adding an additional parameter.
=> Added product recommendation and under $20 list functionality to discord bot

CustomerOrders.java
Added new class CustomerOrders for customers to place an order via email(gmail).
=> Added customer orders through email

Database.java
Now, modify method will take the entered product ID user would like to modify and check if it exists in the database first, giving feedback that it does exist before allowing user to modify the entry. If ID does not exist, it informs the user and exits the modifying function.
=> Added functionality to check if product ID exists in modify method

Main.java
I was having a little fun and added an ascii style menu header with our team name. This is completely optional. If we like it, we can keep it. If not, we can scrap it!
=> Added an IllegalSkillsException menu header

Database.java
Search function within the Orders db now includes Order IDs in the generated report. Also fixed some formatting/spacing.
=> Order ID bug fix

Database.java
Changed read function to return sale price and wholesale prices as doubles rather than ints.
=> Read Function bug fix

CustomerReplyandCancel.java, Database.java, Main.java
The password is missing from the code in the CustomerReplyandCancel class that needs to be added before running. Then the app security on the email needs to be changed to allow unsecure apps to send emails. I have it set to off when I'm not using the email for security reasons.
=> current working code

Database.java, DatabaseConnection.java, Main.java, dataGovernance.java
I created a new class for the initializing the database connection and reorganized the menuLoop() so that the login is only called once and works with all the table changes we want to make.
I have also made it so that the Loop will now ask if you want to keep working on the current database, with a "y" for yes or "n" for no. and then it will ask if you want to work on another database other than your local one.
I was not able to incorporate the the change where the database will use the user logins to provide restricted access to the tables they are not supposed to access so I will need more time for this to work, hopefully it will be ready in the future.
=> fixed menuloop and created new Databaseconnection Class

Main.java
Two exceptions needed to be thrown and an important variable restored. The thrown exceptions should find a more permanent solution in the future.
=> Fixes compilation errors after merge of #61 and #62

Database.java, Main.java
Closes #71. I also had to comment out the email related stuff when inserting or deleting inside of Main.java. I recommend making a new menu option for testing the email stuff.
=> Fixes duplicate entry error when deleting then inserting orders.

Database.java, Main.java
Use .equals() when comparing strings and not ==. They are not the same thing.
=> Generate results method fix

DatabaseConnection.java, DiscordBot.java, ProductRecommend.java
Discord bot now formats outputs from !under20 and !orders commands into code blocks. Added additional code to SQL Exception catch in initializeConnection method in DatabaseConnection.java. Catch statement now asks user to re-enter DB credentials when catching an access denied error and then attempts to run the method again.
=> Fixed Discord bot formatting and added error handling for incorrect DB credentials

Main.java
We can now bypass console password for easier testing of other parts of the program. Running in IDE skips the console password, running in CMD utilizes console password. #82
=> Password console bypass

CustomerOrders.html, styles.css
I created an html for customers to send orders to "our" email. If you wanna check the email to see if the order got sent.
*Username and Password will be in our Teams Group
=> Used html for customers to order

CustomerOrders.java
I'm censoring the title in an attempt to avoid bots. Change the p4.zzw0r/d or risk breach.
=> Removes p4.zzw0r/d from project.

Database.java, DatabaseConnection.java, Main.java
Added export CSV options for all 3 tables. Options found in each corresponding menu. CSV goes to downloads folder. Also updated corrected csv import file name (for the real real real team 3).
=> CSV output

Database.java, Day.java, FinanceReports.java, Main.java, Orders.java, Week.java
Requires the JFreeChart library. This code isn't the best it could be but I have spent quite a while on this already and this level of functionality is sufficient. I will demonstrate it during our meeting.
=> Added in the ability to generate finance report graphs.

Main.java, Orders.java
Added option in Orders menu for exporting marketing reports of best-selling products
=> Marketing Reports

CustomerReplyandCancel.java, Database.java, DiscordBot.java, Main.java, Orders.java
Added RemarketRecommend to Orders.java and customerRecommend to CustomerReplyandCancel.java. RemarketRecommend generates a random product id based on other products purchased at the same time as the original product by other users. Handles cases for when no other products are found or no other users are found. customerRecommend accepts the customer email and product id generated from RemarketRecommend and generates an email listing the product's information.
=> Implemented RemarketingEmails

Orders.java
We can now enter a number of days to filter the report to. Specifically in the best-selling products report option, but can be copied to the best-customers option if needed.
=> Added more functionality to reports

BestCustomer.java, Main.java, Orders.java
Creates customer report for most popular customers.
Note that order table will need to be edited (add subtotal column on the end as DOUBLE) 
AND a new table for customers must be created.
=> Meddy7 customer report

BestCustomer.java, CustomerReplyandCancel.java, DataGovernance.java, Main.java, Orders.java, Users.java
This pull request should finally add data governance to the program. The emails in the orders table will now be hashed. Other functions were modified so as to work with the new method of storing emails.
In order for data governance to work we must make the following edits to the customers SQL tables:
We must also create a new table "emails" to store the unhashed and hashed versions of the emails:
=> Data Governance Completion

Inventory.java, Main.java, Orders.java, Users.java
on methods I built. Will probably add more to it as I go through the program. #104
=> Added in commenting 

BestCustomer.java, Main.java
Finished code. For testing, try any day value larger than 365.
=> Meddy7 bestcustomer2

BestCustomer.java
Unhashes email before exporting.
=> Adds data governance to finding the best customers

CustomerReplyandCancel.java, Database.java, DatabaseConnection.java, DiscordBot.java, Inventory.java, Main.java, Orders.java
Added documentation for all my code. Cleaned up code in both delete functions in Inventory.java and Orders.java as well as their respective menu options. Also added verification for some user input in inventoryTable and ordersTable menus. Cleaned up some code in getRecommend method in Orders.java
=> Added documentation and some code clean up

BestCustomer.java, Orders.java
I did reading into some efficiency options and improved our code's efficiency by disabling MySQL auto commits and executing the batches in stacks of 20 for the two of these. Doing this made the code run in a quarter the time it used to.
=> Improve efficiency of BestCustomer and Orders import.
